/* eslint-disable @typescript-eslint/no-var-requires */
import StyleDictionary from 'style-dictionary';

import config from './config.json';

const styleDictionary = StyleDictionary.extend(config);

styleDictionary.registerFileHeader({
  name: 'nerveTokensHeader',
  fileHeader() {
    return [
      `! DO NOT EDIT THIS TOKENS FILE DIRECTLY!
 * ! THIS FILE WAS GENERATED BY THE BUILD-TOKENS SCRIPT.
 * ***************************************************************************************
 * * Nerve Design Tokens for consumption by Nerve libraries or applications.
 *
 * * If you need to update this file, update the tokens in the 'definitions' folder and
 * * re-run the build-tokens script from 'package.json'.
 * ***************************************************************************************`,
    ];
  },
});

styleDictionary.buildAllPlatforms();
